"""
reset_workspace.py — one-time cleanup script.

Clears all discovered-job / analysis / application data accumulated during
development and testing, while preserving:
  - your standing profile (profile/profile.json, profile/resume_base.md)
  - the Career_Profile and Skills sheets in the CRM (your own reference data)
  - the README and AI_Import_Guide sheets (static instructions)
  - all sheet headers, column widths, and formatting

After running this, the next `python daily.py` (or the web UI's pipeline
buttons) starts from a completely clean slate: fresh discovery, fresh
analysis, fresh kits.

This is meant to be run ONCE, by hand, when you actually want to reset —
it is not part of the normal pipeline and nothing else calls it.

Usage:
    python reset_workspace.py
"""

import shutil
import sys
from pathlib import Path

import openpyxl

BASE = Path(__file__).resolve().parent
CRM_PATH = BASE / "Amaan_Internship_Ecosystem_v2.xlsx"
APPLICATIONS_DIR = BASE / "applications"

# Sheets whose DATA ROWS (everything below the header) get wiped.
# Header row 1 and all formatting/column widths/data validation are kept.
SHEETS_TO_CLEAR = ["Jobs", "AI_Import"]

# Files that hold pipeline run state — safe to delete entirely, they get
# regenerated by the next discover.py / batch_analyzer.py run.
JSON_FILES_TO_DELETE = [
    "jobs_raw.json",
    "jobs_filtered.json",
    "analyses.json",
    "analysis.json",
]


def confirm(prompt):
    answer = input(f"{prompt} [y/N]: ").strip().lower()
    return answer == "y"


def clear_sheet_rows(wb, sheet_name):
    if sheet_name not in wb.sheetnames:
        print(f"  Skipped '{sheet_name}' (sheet not found)")
        return

    ws = wb[sheet_name]
    before = ws.max_row

    if ws.max_row > 1:
        ws.delete_rows(2, ws.max_row - 1)

    print(f"  {sheet_name}: cleared ({before - 1} data rows removed, header kept)")


def delete_json_files():
    for name in JSON_FILES_TO_DELETE:
        path = BASE / name
        if path.exists():
            path.unlink()
            print(f"  Deleted {name}")
        else:
            print(f"  {name} (already absent)")


def clear_applications_dir():
    if not APPLICATIONS_DIR.exists():
        print("  applications/ (already absent)")
        return

    kit_folders = [p for p in APPLICATIONS_DIR.iterdir() if p.is_dir()]
    for folder in kit_folders:
        shutil.rmtree(folder)
    print(f"  Cleared {len(kit_folders)} kit folder(s) from applications/")


def main():
    if not CRM_PATH.exists():
        print(f"ERROR: {CRM_PATH.name} not found in {BASE}")
        sys.exit(1)

    print("This will permanently clear:")
    print(f"  - Job data rows in: {', '.join(SHEETS_TO_CLEAR)} (in {CRM_PATH.name})")
    print(f"  - Generated files: {', '.join(JSON_FILES_TO_DELETE)}")
    print(f"  - All folders under: applications/")
    print()
    print("This will NOT touch:")
    print("  - Career_Profile / Skills sheets (your own profile data)")
    print("  - README / AI_Import_Guide sheets")
    print("  - profile/profile.json, profile/resume_base.md")
    print()

    if not confirm("Proceed with reset?"):
        print("Cancelled — nothing was changed.")
        return

    # Back up the workbook first, since this is a destructive operation
    # on the one file that holds everything.
    backup_path = CRM_PATH.with_name(
        CRM_PATH.stem + "_backup_before_reset" + CRM_PATH.suffix
    )
    shutil.copy2(CRM_PATH, backup_path)
    print(f"\nBacked up workbook → {backup_path.name}")

    print("\nClearing Excel sheets...")
    wb = openpyxl.load_workbook(CRM_PATH, data_only=False)
    for sheet_name in SHEETS_TO_CLEAR:
        clear_sheet_rows(wb, sheet_name)
    wb.save(CRM_PATH)

    print("\nDeleting pipeline state files...")
    delete_json_files()

    print("\nClearing applications/...")
    clear_applications_dir()

    print("\nDone. Run the dashboard step once to reset Morning Dashboard")
    print("and Analytics to zero, e.g.:")
    print(f"    python dashboard.py --crm {CRM_PATH.name}")
    print("\nOr just click '6. Rebuild Dashboard' in the web UI.")
    print("\nAfter that, a fresh 'Run All' will discover and analyze from scratch.")


if __name__ == "__main__":
    main()